# Theme of Diagram
vars: {
  d2-config: {
    # Terminal theme code
    theme-id: 200
  }
}

title: |md
# System Architecture Diagram v2.0.0
| {near: top-center}

direction: down

Krita: {
  shape: image
  icon: ./icons/krita_logo.svg
}

Storyboarder: {
  shape: image
  icon: ./images/storyboarder_icon.png
}

Blender: {
    shape: image
    icon: ./icons/blender.svg
}

Godot: {
    shape: image
    icon: ./icons/godot.svg
}

Github: {
    shape: image
    icon: ./icons/github_white.svg
}

Project Manager: {
    shape: image
    icon: ./icons/jira.svg
}

Storyboarder -> Storyboards: Draw
Storyboards -> AandR: Export as reference for 3d artist
Krita -> Concept Art: Create concept art
Concept Art -> Material: lighting, colors, textures
Concept Art -> Texture: 2d patterns
Krita -> Models: Create Character Turnaround
Krita -> Models: Character Iterations

AandR: "Animation & Rigging"
AandR -> Blender: Design rigs and animations
Texture -> Blender: Import Textures
Material -> Blender: Import Materials
Models -> Blender: Design Models

Blender -> Assets: Export Models
Blender -> Animations: Export Animations
Blender -> Textures: Export Textures
Assets -> Godot: Import Models
Animations -> Godot: Import Animations
Textures -> Godot: Import Textures
SoundEffects -> Godot: Import Sound Effects
Godot -> Scripts: Create GD scripts
Scripts -> Godot: Use Game Scripts
Blender -> GitHub: Commit 3D Models
GitHub -> Godot: Sync Game Project
Project Manager -> GitHub: Track Issues and Tasks
Godot -> GitHub: Commit Game Project